name: local_data_source
description: A universal, engine-agnostic local database abstraction layer for Flutter.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  meta: ^1.17.0
  path_provider: ^2.1.5


dev_dependencies:
  isar_community_generator: ^3.3.0
  hive_ce_generator: ^1.9.3
  build_runner: ^2.7.1
